// <auto-generated />
using Fiap.Web.AspNet.Persistences;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace _07Fiap.Web.AspNet.Migrations
{
    [DbContext(typeof(BancoContext))]
    [Migration("20190919134923_v2")]
    partial class v2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Fiap.Web.AspNet.Models.Condominio", b =>
                {
                    b.Property<int>("CondominioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Ativo");

                    b.Property<int>("Blocos");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(40);

                    b.Property<int>("SindicoId");

                    b.Property<int>("Tipo");

                    b.HasKey("CondominioId");

                    b.HasIndex("SindicoId");

                    b.ToTable("TCondominio");
                });

            modelBuilder.Entity("Fiap.Web.AspNet.Models.CondominioConstrutora", b =>
                {
                    b.Property<int>("CondominioId");

                    b.Property<int>("ConstrutoraId");

                    b.HasKey("CondominioId", "ConstrutoraId");

                    b.HasIndex("ConstrutoraId");

                    b.ToTable("CondominioConstrutora");
                });

            modelBuilder.Entity("Fiap.Web.AspNet.Models.Construtora", b =>
                {
                    b.Property<int>("ConstrutoraId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cnpj");

                    b.Property<string>("Nome");

                    b.HasKey("ConstrutoraId");

                    b.ToTable("Construtoras");
                });

            modelBuilder.Entity("Fiap.Web.AspNet.Models.Imovel", b =>
                {
                    b.Property<int>("ImovelId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float>("AreaUtil");

                    b.Property<int>("CondominioId");

                    b.Property<string>("Numero");

                    b.HasKey("ImovelId");

                    b.HasIndex("CondominioId");

                    b.ToTable("Imoveis");
                });

            modelBuilder.Entity("Fiap.Web.AspNet.Models.Sindico", b =>
                {
                    b.Property<int>("SindicoId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email");

                    b.Property<string>("Nome");

                    b.HasKey("SindicoId");

                    b.ToTable("Sindicos");
                });

            modelBuilder.Entity("Fiap.Web.AspNet.Models.Condominio", b =>
                {
                    b.HasOne("Fiap.Web.AspNet.Models.Sindico", "Sindico")
                        .WithMany()
                        .HasForeignKey("SindicoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Fiap.Web.AspNet.Models.CondominioConstrutora", b =>
                {
                    b.HasOne("Fiap.Web.AspNet.Models.Condominio", "Condominio")
                        .WithMany("CondominioConstrutoras")
                        .HasForeignKey("CondominioId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Fiap.Web.AspNet.Models.Construtora", "Construtora")
                        .WithMany("CondominioConstrutoras")
                        .HasForeignKey("ConstrutoraId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Fiap.Web.AspNet.Models.Imovel", b =>
                {
                    b.HasOne("Fiap.Web.AspNet.Models.Condominio", "Condominio")
                        .WithMany("Imoveis")
                        .HasForeignKey("CondominioId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
